### ISSUE TITLE
Preprocessing code

### ISSUE THREAD

**Issue by Fujiry0** [vita-epfl/social-transmotion#2]
Hi! @SaeedSaadatnejad @yanggao2000 

Thank you for your excellent work.
Could you please share your preprocessing code? 

Is the JRDB preprocessing code the same as JRDB-Traj?

Thanks in advance,

**Comment by SaeedSaadatnejad** [comment]
Hi, thank you.
The preprocessing code of JTA needs a bit of cleaning. We hope to release it soon.
For the JRDB, as you mentioned, we used the preprocessing code of [JRDB-Traj](https://github.com/vita-epfl/JRDB-Traj/).

**Comment by Fujiry0** [comment]
Thank you! I'm looking forward to future release!

**Comment by yanggao2000** [comment]
Hi! @Fujiry0,

Thank you! I uploaded the preprocessing code for JTA dataset here https://drive.google.com/drive/folders/1iIp2B5y85OKZ7DkW7gBkmulUxMWW5SkY?usp=sharing
You can use it to get the the similar preprocessed JTA data as we used as train/val/test splits in our paper. Please note that the used seed was different so the generated scenes could be a little different.
Feel free to let me know if you have further question.

**Comment by Fujiry0** [comment]
@yanggao2000 Thank you so much!
