### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by ldx5972** [vita-epfl/social-transmotion#5]
Hello Sir, thanks for your work. Currently, I have a problem when learning your code, and the dataset I generated according to the JTA official  tutorial cannot be adapted to your code, I wonder if you can answer the question how to generate the data set? thank you.

**Comment by SaeedSaadatnejad** [comment]
Hello, please refer to this [issue](https://github.com/vita-epfl/social-transmotion/issues/2) thread.

**Comment by ldx5972** [comment]
> Hello, please refer to this [issue](https://github.com/vita-epfl/social-transmotion/issues/2) thread.

Thank you!!!
