### ISSUE TITLE
LOSS is "NAN"

### ISSUE THREAD

**Issue by gaotianci99** [vita-epfl/social-transmotion#7]
Hello, thanks for the author's works. I hava preprocessed the data,  and this is my project dir:
![image](https://github.com/vita-epfl/social-transmotion/assets/126347638/b379789b-03d9-43fe-b166-a63983b5e2f1)
I trained the JTA dataset using a single TeslaV100 GPU for 2 days, however, in the last 10~15  epoches, the loss turn to "NAN"  . I wonder if the author faced this problem and how to sovle it?
![image](https://github.com/vita-epfl/social-transmotion/assets/126347638/49a7f809-dfc0-4f98-9473-2632f21f2fc2)

**Comment by yanggao2000** [comment]
Hi, thanks for reaching out.
The data directory looks okay. Regarding the loss issue, actually we haven't faced the issue before. Maybe could you double-check if you changed anywhere or followed all the provided instructions? Thanks.
