### ISSUE TITLE
Dataset other than JTA or JRDB

### ISSUE THREAD

**Issue by ImIntheMiddle** [vita-epfl/social-transmotion#8]
Hi, thank you for sharing your fantastic work and code!

In your paper, you conducted experiments with datasets such as Pedestrians and Cyclists in Road Traffic. Would it be possible for you to share the source code for the data processing and models used in those experiments?

Thank you in advance! 😊

**Comment by ImIntheMiddle** [comment]
Or if you plan to add code in the future, could you let me know the ETA for that, please? Thanks!

**Comment by SaeedSaadatnejad** [comment]
Hi, thank you for your interest. At the moment, we do not have plans to release the data and models from that dataset. We will keep you informed if anything changes

**Comment by ImIntheMiddle** [comment]
Understood. Thank you for your kind response!
